### PR TITLE
Fixed incorrect single select option styling

### LINKED ISSUE #90: Bug: Incorrect single-select option styling

### PR DESCRIPTION
**Pull request by villejuutila**
Resolves #90 
Also fixes bug that caused all survey pages to be updated when just one has been edited
Also always shows delete icon for question option

### CODE REVIEW

File: src/utils/page-utils.ts [hunk 1]
```diff
@@ -320,9 +332,12 @@ namespace PageUtils {
     const innerHTMLValues: string[] = [];
 
     tempContainer.childNodes.forEach((childNode) => {
+      console.log(childNode);
```
Comment (Jdallos) [inline src/utils/page-utils.ts:335]: Remove console log

**Review by Jdallos — APPROVED** [review]
Approved with a comment

File: src/utils/page-utils.ts (hunk 1 above)
Comment (villejuutila) [reply src/utils/page-utils.ts]: Resolved.
